### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by secretnumber** [MarinX/btc-vanity#2]
Hello!

Could you please explain how to use this program?

```go get github.com/MarinX/btc-vanity``` installs the package but no executable. Not sure how to proceed from there.

Cloning it and running ```go build``` from that directory doesn't do anything either. What am I missing?

I'm new to go, so excuse my ignorance.

**Comment by MarinX** [comment]
Hey @secretnumber ,
This is a library, not a cli tool, which means this should be used in your packages or software.

But, it's easy to add a cli tool, so, check out my latest version which includes a simple CLI tool.
The README is updated.

To use it as CLI tool, you need to
```sh
go get github.com/MarinX/btc-vanity/cmd/btcvanity
```
Now you should have a bin called `btcvanity` which is in your GOPATH/bin.

Let me know if this solves your issue or if you need help.

**Comment by secretnumber** [comment]
That's perfect, thank you. I will check it shortly and report back if I encounter any issues.
