### ISSUE TITLE
Segwit support

### ISSUE THREAD

**Issue by DeadNumbers** [MarinX/btc-vanity#3]
Hi! Is this lib supported segwit addresses?

**Comment by MarinX** [comment]
Hi.
This lib is just a client to Electrum server (your local instance).
The latest version of Electrum as of this writing is 3.3.8 which supports segwit addresses in bech32 format.

**Comment by MarinX** [comment]
Hi,
No, this lib does not support segwit addresses.
It generates only a legacy btc address.
